language: python
dist: xenial
python:
- '3.6'
- '3.7'
- nightly
script:
- echo "there are no tests yet:-("
install:
- python setup.py sdist
deploy:
  distributions: sdist
  on:
    tags: true
  provider: pypi
  user: "enigma@nbubu.de"
  password:
    secure: "BBl1PpvoXb01DZ4iuESdpsZOcCf6LhNW2Lo6Jqlrx+fbKJIqAfciVu7CLMrAh1J8UxOUnIQS5+pBF9NQGvSBBqQha2cdcqT1LVjw4FKGDOVO21xp5o6EnMCayVD94yNs+m4ZDkGoEMp3NklfdLp7nfd9urnjVQfQcvDoU3eCrhEXkl2DF0vWIyTk4WY/A+AH6YJm1e+enjz5hWf9j81p0jJQ4t9U6EDiNfHtylZq/q5ntWqH6ZsslUqDvDitp8lPkCWOZKL0MK/1Eu+8V2zwxYLtwCOAkHCj5oPquh6PSNQRI1wJp+K066RR6xMTkYFadtimc/J7gwGN28QZ3iXKeeXXriAVdJG0/4bzE8ymEYSkg2BmJY9IiaG/LuABZZWBXno9IZxppgt8zbXhM30UtgsHF8iVYKaQg+xYbHe1AlUTCii7af8Epct8cYMua1IeQSkb62I5VMISmerqTRjqoylcfJU/8tNrJ2Y66ncFdW2WqllyVhzacXmWXYmi+WOjZakg9Me+pvRiYpC0JPHV1FhOMLokwZ01L+H5YQpZvXDjD2zObu3kuP+Lw/EThJSaQvSArZGsxpWrSjphMmZBTDdA3z3NjKW1Z97qRleSZjBtCobBYwFBzo3uxgMRDcJO4U/CDowuN2xCHJGAyw0Flly4GyY/2jlayIdgUtWJv3U="
